### ISSUE TITLE
more detailed description for installation

### ISSUE THREAD

**Issue by minusplusminus** [olragon/graphql_api#1]
Hi Olagon,

I've managed to install the GraphQL module with all de deps and installed all the deps with composer. I see that GraphQL-php is in the vendor dir. 

I want to know what the steps after that are?

the error i'm currently having is:

`
Fatal error: Class 'GraphQL\Type\Definition\ObjectType' not found in /Users/martijnmellema/Documents/Development/Projecten/Djeepo/djeepo/sites/all/modules/graphql_api/graphql_api.graphql.inc on line 16`

Kind regards!

**Comment by minusplusminus** [comment]
Oh wait, found out that I had to run  `composer install` inside the `default/files/composer` dir.

one step closer :)


current error I get

`{
    "errors": [{
        "message": "Cannot convert field_item_textsummary to GraphQL type.Array\n(\n    [entity_type] =\u003E node\n    [bundle] =\u003E unit\n    [property] =\u003E body\n    [info] =\u003E Array\n        (\n            [label] =\u003E Description\n            [type] =\u003E field_item_textsummary\n            [description] =\u003E Veld \u0027body\u0027.\n            [getter callback] =\u003E entity_metadata_field_verbatim_get\n            [setter callback] =\u003E entity_metadata_field_verbatim_set\n            [access callback] =\u003E entity_metadata_field_access_callback\n            [translatable] =\u003E \n            [field] =\u003E 1\n            [required] =\u003E \n            [property info] =\u003E Array\n                (\n                    [value] =\u003E Array\n                        (\n                            [type] =\u003E text\n                            [label] =\u003E Tekst\n                            [setter callback] =\u003E entity_property_verbatim_set\n                        )\n\n                    [summary] =\u003E Array\n                        (\n                            [type] =\u003E text\n                            [label] =\u003E Samenvatting\n                            [setter callback] =\u003E entity_property_verbatim_set\n                        )\n\n                )\n\n            [auto creation] =\u003E entity_property_create_array\n        )\n\n)\n",
        "backtrace": [{
            "function": "graphql_api_page_callback",
            "args": ["explorer"]
        }, {
            "file": "/includes\/menu.inc",
            "line": 527,
            "function": "call_user_func_array",
            "args": ["graphql_api_page_callback", ["explorer"]]
        }, {
            "file": "\\/djeepo\/index.php",
            "line": 24,
            "function": "menu_execute_active_handler",
            "args": []
        }]
    }]
}`


`{"errors":[{"message":"Schema must contain unique named types but contains multiple types named \u0022taxonomy_term\u0022.","backtrace":[{"function":"graphql_api_page_callback","args":["explorer"]},{"file":"\/Users\/martijnmellema\/Documents\/Development\/Projecten\/Djeepo\/djeepo\/includes\/menu.inc","line":527,"function":"call_user_func_array","args":["graphql_api_page_callback",["explorer"]]},{"file":"\/Users\/martijnmellema\/Documents\/Development\/Projecten\/Djeepo\/djeepo\/index.php","line":24,"function":"menu_execute_active_handler","args":[]}]}]}`


`Error: node.body expects type "text_formatted" but unit.body provides type "field_item_textsummary".
    at n (chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:6:12077)
    at chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:8:15684
    at Array.forEach (native)
    at a (chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:8:15535)
    at Array.forEach (native)
    at chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:8:18291
    at Array.forEach (native)
    at new e (chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:8:18199)
    at o (chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:24:31688)
    at chrome-extension://mcbfdonlkfpbfdpimkjilhdneikhfklp/js/app.bundle.js:23:24165`

**Comment by olragon** [comment]
@minusplusminus what is field type of `field_item_textsummary`?

**Comment by minusplusminus** [comment]
According to the Drupal sourcecode: 

` $field_info['text_with_summary']['property_type'] = 'field_item_textsummary';
    $field_info['text_with_summary']['property_callbacks'][] = 'entity_metadata_field_text_property_callback'; `


[link](http://www.drupalcontrib.org/api/drupal/contributions!entity!includes!entity.property.inc/function/entity_field_info_alter/7)

working in Drupal 7.43

**Comment by olragon** [comment]
I have just publish internal code contain fix for field type "Text with summary", give it a try.

https://github.com/olragon/graphql_api/commit/266b9bb0a8e577970d869dcce6dbb6b8af16cd7c
