### ISSUE TITLE
Error with Composer Manager Security Advisory module during installation

### ISSUE THREAD

**Issue by d0t15t** [olragon/graphql_api#10]
Hi,

i'm writing in follow-up to the conversation on https://github.com/olragon/graphql_api/issues/9

During installation with drush i get the following messages and errors:

```
It is recommended to enable the Composer Manager Security Advisory module to[status]
automatically check for security updates.
One or more extensions have dependencies managed by Composer.
Update packages managed by Composer? (y/n): y
Download and install the Drush Composer extension? (y/n): y
Project composer (8.x-1.x-dev) downloaded to /Users/ibt/.drush/composer.    [success]
Project composer contains 0 modules: .
The drush command 'composer' could not be found.                            [error]
RuntimeException: Autoloader not found:                                     [error]
/Users/ibt/Sites/devdesktop/fhp-portal/drupal/docroot/sites/all/vendor/autoload.php
```

It's looking for composer in the wrong directory.

**Comment by olragon** [comment]
Hi @dotist 

I believe error come from Drush Composer extension.
You can try again by remove Drush Composer extension (`rm -r ~/.drush/composer && drush cc all`) and follow my installation process:

```bash
drush composer-json-rebuild
cd sites/default/files/composer
composer update
```
assume command `drush` & `composer` available

**Comment by d0t15t** [comment]
Hi @olragon 

thanks for your quick response! I was able to fix the problem by re-installing composer-manager seperately as per the directions here https://www.drupal.org/node/2405805.
After that, installation for graphql_api completed successfully.
