### ISSUE TITLE
Error on /graphqleditor

### ISSUE THREAD

**Issue by d0t15t** [olragon/graphql_api#11]
After basic installation with [Composer Manager Security Advisory error](https://github.com/olragon/graphql_api/issues/10), the right panel on **/graphqleditor** returns the error: `SyntaxError: Unexpected token < in JSON` See attached image. 
![graphqleditor-error](https://user-images.githubusercontent.com/3645818/41600187-7a1bce40-73d5-11e8-874a-30fbadaa83bd.png)

**Comment by olragon** [comment]
blocked by #10

**Comment by d0t15t** [comment]
Hi @olragon 

although #10 is resolved, and the module plus dependencies have installed correctly, i still get the same error at **/graphqleditor**.

**Comment by olragon** [comment]
Look like server can't return JSON inspection. 
Can you use give me more info?
You can view full response at `Chrome Developer Tools -> Network -> request /graphql -> Response`

**Comment by d0t15t** [comment]
Is this the correct debugging information? It appears to be related to the same field in #12.

![devtools_-_fhp_dd_8083_graphqleditor_and_error_on__graphqleditor_ _issue__11_ _olragon_graphql_api](https://user-images.githubusercontent.com/3645818/41647905-d2c1d7fe-7477-11e8-8362-a4f251269752.png)

**Comment by olragon** [comment]
Yes it is, #12 is related, I will close this issue
