### ISSUE TITLE
Error on /graphql 'Try to resolve interface to object'

### ISSUE THREAD

**Issue by d0t15t** [olragon/graphql_api#12]
On the page, it reads out about 100 lines of variables and then the error: `Try to resolve interface to object in field level failed. field_country node`

**Comment by olragon** [comment]
What is field type of `field_country`?

**Comment by d0t15t** [comment]
The field is from the [Countries](https://www.drupal.org/project/countries) module. Country-Objects are Drupal-Entities, however the referencing field is not a basic entity-reference, but instead something specific to the Countries module.

**Comment by olragon** [comment]
We need define GraphQL object type for this special field type.
You can see https://github.com/olragon/graphql_api/blob/master/graphql_api.graphql.inc for reference.

You can declare this field type using these steps:
- In your module, create file [your_module].graphql.inc
- Implement hook_graphql_api_info()
- Clear cache

**Comment by d0t15t** [comment]
Thanks! I'll try it right now.

**Comment by d0t15t** [comment]
I've implemented the hook in `<module>.graphql.inc`, but am not having any luck. Do you have any other suggestions of where else i could look to take clues for debugging? I based my values on [countries_entity_info()](https://cgit.drupalcode.org/countries/tree/countries.module?id=21eae4f35f4a9b859831f20cf93db56fafa2ca05) Thanks so much!

```
<?php

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;

/**
 * Implements hook_graphql_api_info().
 */

function <module>_graphql_api_info() {
  return array(
    'types' => array(
      'field_item_country' => new ObjectType(array(
        'name' => 'field_item_country',
        'fields' => function () {
          $schema = graphql_api();
          $file_type = $schema->getObjectType('countries_country');
          $t=1;
          if (module_exists('countries')) {
            $file_type = $schema->getInterfaceType('country');
          }
          return array(
            'cid' => array(
              'type' => Type::string(),
              'description' => t('Country ID')
            ),
            'iso2' => array(
              'type' => Type::string(),
              'description' => t('ISO2')
            ),
            'name' => array(
              'type' => Type::string(),
              'description' => t('Name')
            ),
          );
        }
      )),
    ),
  );
}

```

**Comment by olragon** [comment]
I think Object type name should be `field_country` accord to error message.

Could you try this.
```php
<?php

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;

/**
 * Implements hook_graphql_api_info().
 */

function <module>_graphql_api_info() {
  return array(
    'types' => array(
      'field_country' => new ObjectType(array(
        'name' => 'field_country',
        'fields' => function () {
          return array(
            'cid' => array(
              'type' => Type::string(),
              'description' => t('Country ID')
            ),
            'iso2' => array(
              'type' => Type::string(),
              'description' => t('ISO2')
            ),
            'name' => array(
              'type' => Type::string(),
              'description' => t('Name')
            ),
          );
        }
      )),
    ),
  );
}
```

**Comment by d0t15t** [comment]
I should have thought of that! Unfortunately though, that doesn't resolve the problem.

**Comment by d0t15t** [comment]
I found the `$blacklist` variable in Schema.php and tested out adding 'countries' and 'field_country' to the array. For 'countries' it then returns a different error: outputting entity schema-like data of all the entities (see screenshot). I started going through the list, adding each entity-type to the list: 'field_collection_item', 'comment', and so forth. Eventually also 'node' came up, so i guess i won't be able to 'blacklist' it into working. Any clue where this new error is coming from, and why blacklisting 'countries' isn't working? Thanks!

**Comment by d0t15t** [comment]
![fhp_dd_8083_graphql](https://user-images.githubusercontent.com/3645818/41715871-0e2c9990-7555-11e8-842a-4dbc62f727f7.png)

**Comment by olragon** [comment]
I have just merge Github code with internal code. Please update (branch master or 7.x-2.x)

**Comment by dotist** [comment]
Hi, thanks for the update! It's looking better - now throwing the following errors (see images).
![fhp_dd_8083_graphql 2](https://user-images.githubusercontent.com/3645818/41768042-7eb4bef2-760b-11e8-8c58-517c5e52808c.png)
![graphiql___fisch-hitparade](https://user-images.githubusercontent.com/3645818/41768043-7ee24e62-760b-11e8-85ea-e7c1c083e1c8.png)

**Comment by d0t15t** [comment]
It works!

**Comment by d0t15t** [comment]
Thanks so much! : )

**Comment by Jehu** [comment]
yeah! many thanks @olragon
