### ISSUE TITLE
Support for Paragraphs?

### ISSUE THREAD

**Issue by klokie** [olragon/graphql_api#3]
Hello! I have a [Paragraphs](https://www.drupal.org/project/paragraphs) field that I would like to access via the GraphQL endpoint. However it seems like the only fields available in the schema are those raw properties of the field itself (`archived`, `bundle`, `field_name`, `item_id`, `revision_id`). 

I can see that the paragraphs fields I want to access (e.g. `body`, `images`, etc) are accessible via the individual paragraph bundles (e.g. `bundle1{body}`, `bundle2{images}` etc), I would love to be able to access the fields directly within the `node` query, just like entity reference and taxonomy reference fields now work. What would be required for that to work? 

Please let me know if this is unclear.
Thanks!

**Comment by olragon** [comment]
https://github.com/olragon/graphql_api/commit/266b9bb0a8e577970d869dcce6dbb6b8af16cd7c

New code should fix your issue, please update

**Comment by klokie** [comment]
That works great - thanks so much!
