### ISSUE TITLE
Error trying to convert link, name, or socialfield to GraphQL type

### ISSUE THREAD

**Issue by klokie** [olragon/graphql_api#4]
Similarly to #1 & #3, this module throws an error when trying to serialize fields of the following types:
1. [List](https://www.drupal.org/project/list)
2. [Name Field](https://www.drupal.org/project/name)
3. [Social field](https://www.drupal.org/project/socialfield)

For example,
1. [List](https://www.drupal.org/project/list)
```
array(4) { 
["entity_type"]=> string(8) "profile2" 
["bundle"]=> NULL 
["property"]=> string(20) "field_relevant_links" 
["info"]=> array(11) { 
["label"]=> string(25) "Additional Personal Links" 
["type"]=> string(21) "list" 
["description"]=> string(29) "Field "field_relevant_links"." 
["getter callback"]=> string(34) "entity_metadata_field_verbatim_get" 
["setter callback"]=> string(34) "entity_metadata_field_verbatim_set" 
["access callback"]=> string(37) "entity_metadata_field_access_callback" 
["translatable"]=> bool(false) 
["field"]=> bool(true) 
["required"]=> bool(false) 
["auto creation"]=> string(22) "link_field_item_create" 
["property info"]=> array(3) { 
["title"]=> array(4) { 
["type"]=> string(4) "text" 
["label"]=> string(22) "The title of the link." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["required"]=> bool(true) } 
["url"]=> array(4) { 
["type"]=> string(3) "uri" 
["label"]=> string(20) "The URL of the link." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["required"]=> bool(true) } 
["attributes"]=> array(4) { 
["type"]=> string(6) "struct" 
["label"]=> string(27) "The attributes of the link." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["getter callback"]=> string(27) "link_attribute_property_get" } } } }
Cannot convert field_item_link to GraphQL type.
```

2. [Name Field](https://www.drupal.org/project/name)

```
array(4) { 
["entity_type"]=> string(8) "profile2" 
["bundle"]=> NULL 
["property"]=> string(27) "field_contributor_full_name" 
["info"]=> array(11) { 
["label"]=> string(9) "Full Name" 
["type"]=> string(15) "field_item_name" 
["description"]=> string(36) "Field "field_contributor_full_name"." 
["getter callback"]=> string(34) "entity_metadata_field_verbatim_get" 
["setter callback"]=> string(34) "entity_metadata_field_verbatim_set" 
["access callback"]=> string(37) "entity_metadata_field_access_callback" 
["translatable"]=> bool(false) 
["field"]=> bool(true) 
["required"]=> bool(false) 
["auto creation"]=> string(22) "name_field_item_create" 
["property info"]=> array(3) { 
["given"]=> array(4) { 
["type"]=> string(4) "text" 
["label"]=> string(15) "The given name." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["required"]=> bool(false) } 
["middle"]=> array(4) { 
["type"]=> string(4) "text" 
["label"]=> string(23) "The middle of the name." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["required"]=> bool(false) } 
["family"]=> array(4) { 
["type"]=> string(4) "text" 
["label"]=> string(23) "The family of the name." 
["setter callback"]=> string(28) "entity_property_verbatim_set" 
["required"]=> bool(false) } } } }
Cannot convert field_item_name to GraphQL type.
```

3. [Social field](https://www.drupal.org/project/socialfield)

```
array(4) { 
["entity_type"]=> string(8) "profile2" 
["bundle"]=> NULL 
["property"]=> string(18) "field_social_links" 
["info"]=> array(9) { 
["label"]=> string(12) "Social Links" 
["type"]=> string(11) "socialfield" 
["description"]=> string(27) "Field "field_social_links"." 
["getter callback"]=> string(34) "entity_metadata_field_verbatim_get" 
["setter callback"]=> string(34) "entity_metadata_field_verbatim_set" 
["access callback"]=> string(37) "entity_metadata_field_access_callback" 
["translatable"]=> bool(false) 
["field"]=> bool(true) 
["required"]=> bool(false) } }
Cannot convert socialfield to GraphQL type.
```

(note that in these examples I've added the field to [Profile 2](https://www.drupal.org/project/profile2) entities, but I've seen the same error when they are attached to other bundles.)

**Comment by olragon** [comment]
- Error convert Drupal type -> GraphQL type shouldn't prevent grahpql_api to work with https://github.com/olragon/graphql_api/commit/eb73ac43a9460e4a6e41e26490905862578c0852

- Field type social, name should be supported with this commit https://github.com/olragon/graphql_api/commit/a8aa87da8762267412381bc286d144a389ddbd4c. 

- graphql_api will not support _List_ because it isn't follow Drupal's module standard, you can use `hook_graphql_api_info()` to register GrahpQL type of list by yourself.

**Comment by klokie** [comment]
It looks like errors are handled much better now, thanks for that!
Also, Name Field and Social field are working as expected.

I meant that fields from the [Link](https://www.drupal.org/project/link) module weren't working, not the "list" module (which is much less popular and, as you write, fails to follow Drupal's module standard). Sorry for the confusion.

I'm currently investigating into if this could be related to one of the following open issues:
* [entity_property_query() error loading link field [#1698198]](https://www.drupal.org/node/1698198)
* [property type for 'url' entity metadata property should not be 'url' [#2558497]](https://www.drupal.org/node/2558497)

**Comment by olragon** [comment]
Partial support for [Link](https://www.drupal.org/project/link) is here https://github.com/olragon/graphql_api/commit/ec16e988f5c1cd1327fdff39e4045d21a824b112
