### ISSUE TITLE
filter support / filter by url

### ISSUE THREAD

**Issue by klokie** [olragon/graphql_api#7]
Hello,
I'm wondering if this module supports the `filter` parameter for a query?
When I submit the following query,
```
query node_article {
  node(filter:{ url: "foo" }) {
    nid
    title
    url
  }
}
```
…I get the response:
```
{
  "errors": [
    {
      "message": "Unknown argument \"filter\" on field \"node\" of type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 8
        }
      ]
    }
  ]
}
```

Is there a way to make this work? Or maybe some other, easier way to filter results by url?
The `url` field doesn't seem to be supported by the current resolvers.
Thanks

**Comment by olragon** [comment]
Did `url` is database's columns or virtual entity metadata property? I think we cannot filter by virtual meta data property.

For database property. You can implement hook `graphql_api_query_info_alter` to do this.
Pseudo code
```
function your_module_graphql_api_query_info_alter(&$queryTypeInfo, &$schema) {
  // do whatever you need with $queryTypeInfo
}
```
