### ISSUE TITLE
Breaks on simplytest.me

### ISSUE THREAD

**Issue by geek-merlin** [olragon/graphql_api#8]
Just tried it on simplytest.me. Querying /graphql path yields:
> Fatal error: Class 'GraphQL\Type\Definition\ObjectType' not found in /home/duxux/www/sites/default/modules/graphql_api/graphql_api.graphql.inc on line 16

Should this work?
Is this module functional?
Also: What i didn't grok from the source: Does this support mutation queries?

In any case: Thanks a lot for this!

**Comment by olragon** [comment]
1/ I don't think simpletest.me can properly install this module.
This module require library https://github.com/webonyx/graphql-php through module https://drupal.org/project/composer_manager

2/ mutation is not yet supported

**Comment by geek-merlin** [comment]
Thanks for the quick response!

**Comment by Jehu** [comment]
> 2/ mutation is not yet supported

@olragon is this still the case? mutations are not implemented yet?

**Comment by olragon** [comment]
mutation is implemented, mutation field is suffix by 
- `_save` for created, update. Eg: `node_save`, `user_save`, etc ...
- `_delete` for delete. Eg: `node_delete`

![image](https://user-images.githubusercontent.com/47636/42766887-c75df0e0-8945-11e8-985c-2fe9f62e0583.png)
