### ISSUE TITLE
is the development stopped - how can we finalize it?

### ISSUE THREAD

**Issue by Jehu** [olragon/graphql_api#9]
i am interested in using your module in a project but it seems incomplete.
would you be interested in finishing the module for a bounty / sponsoring?

**Comment by olragon** [comment]
Due to other works, development is stopped.
What's area of incomplete do you feeling?

Some other hack/improvements stuck in our private repos, need to find some time to clean it up and push it here.

**Comment by Jehu** [comment]
My colleague writes me:

> 1) After installing its failed to show any thing on /graphqleditor url
> 2) Variable graphql_token is not getting set from anywhere ( need admin for this) this will bypass the user_access
> 3) // FIXME tags are on code

**Comment by olragon** [comment]
Can you or your colleague create separated issues with error message so I can look deeper?

**Comment by Jehu** [comment]
thanks so much for your help!
